"""
Data dictionary exporter: generates Markdown or CSV schema documentation.

Produces human-readable, shareable documentation — ideal for product managers
and stakeholders who want to understand a data model without reading raw SQL.
"""

import csv
import io
import re


class DataDictExporter:
    """Generates a data dictionary (Markdown or CSV) from an analysis result."""

    def generate_markdown(self, analysis: dict) -> str:
        """
        Generate a Markdown data dictionary documenting all tables and columns.

        Includes an overview table, per-table column documentation, and sample
        queries formatted as fenced SQL code blocks.
        """
        ui_type = analysis.get("ui_type", "Unknown UI")
        confidence = analysis.get("confidence", 0.0)
        description = analysis.get("description", "")
        analyzed_at = analysis.get("_analyzed_at", "")
        is_mock = analysis.get("_mock", False)
        model = analysis.get("_model", "")
        entities = analysis.get("entities", [])
        queries = analysis.get("sample_queries", [])

        total_cols = sum(len(e.get("fields", [])) for e in entities)
        fk_count = sum(
            1
            for e in entities
            for f in e.get("fields", [])
            if "REFERENCES" in f.get("constraints", "").upper()
        )

        lines = [
            f"# Data Dictionary: {ui_type}",
            "",
            "## Overview",
            "",
            "| Property | Value |",
            "|----------|-------|",
            f"| **UI Type** | {ui_type} |",
            f"| **Confidence** | {confidence:.0%} |",
        ]
        if description:
            lines.append(f"| **Description** | {description} |")
        if analyzed_at:
            lines.append(f"| **Analyzed At** | {analyzed_at} |")
        if model:
            lines.append(f"| **Model** | {model} |")
        if is_mock:
            lines.append("| **Mode** | demo/mock |")
        lines += [
            f"| **Tables** | {len(entities)} |",
            f"| **Total Columns** | {total_cols} |",
            f"| **Foreign Keys** | {fk_count} |",
            "",
        ]

        # Table of contents
        lines.append("## Tables")
        lines.append("")
        for entity in entities:
            anchor = entity["name"].lower().replace("_", "-")
            col_count = len(entity.get("fields", []))
            lines.append(f"- [`{entity['name']}`](#{anchor}) — {col_count} columns")
        lines.append("")

        # Per-table documentation
        for entity in entities:
            name = entity["name"]
            desc = entity.get("description", "")
            fields = entity.get("fields", [])

            lines.append("---")
            lines.append("")
            lines.append(f"## `{name}`")
            if desc:
                lines.append("")
                lines.append(f"> {desc}")
            lines.append("")
            lines.append(f"**{len(fields)} column(s)**")
            lines.append("")
            lines.append("| Column | Type | Constraints | Notes |")
            lines.append("|--------|------|-------------|-------|")

            for field in fields:
                col_name = field["name"]
                col_type = field["type"]
                constraints = field.get("constraints", "")
                notes = _field_notes(constraints)
                lines.append(
                    f"| `{col_name}` | `{col_type}` | `{constraints}` | {notes} |"
                )
            lines.append("")

        # Sample queries
        if queries:
            lines += [
                "---",
                "",
                "## Sample Queries",
                "",
            ]
            for q in queries:
                lines.append(f"### {q.get('description', 'Query')}")
                lines.append("")
                lines.append("```sql")
                lines.append(q.get("sql", "").strip())
                lines.append("```")
                lines.append("")

        lines += [
            "---",
            "",
            "_Generated by [Screenshot2SQL](https://heyneo.so)_",
            "",
        ]
        return "\n".join(lines)

    def generate_csv(self, analysis: dict) -> str:
        """
        Generate a CSV data dictionary with one row per column.

        Columns: table, column, type, constraints, is_pk, is_fk, fk_ref,
                 is_unique, table_description
        """
        entities = analysis.get("entities", [])
        output = io.StringIO()
        writer = csv.writer(output, quoting=csv.QUOTE_ALL)

        writer.writerow([
            "table",
            "column",
            "type",
            "constraints",
            "is_pk",
            "is_fk",
            "fk_ref",
            "is_unique",
            "table_description",
        ])

        for entity in entities:
            table_name = entity["name"]
            table_desc = entity.get("description", "")
            for field in entity.get("fields", []):
                col = field["name"]
                col_type = field["type"]
                constraints = field.get("constraints", "")
                upper_c = constraints.upper()

                is_pk = "PRIMARY KEY" in upper_c
                is_fk = "REFERENCES" in upper_c
                is_unique = "UNIQUE" in upper_c

                fk_ref = ""
                if is_fk:
                    m = re.search(
                        r"REFERENCES\s+(\w+)\s*\((\w+)\)", constraints, re.IGNORECASE
                    )
                    if m:
                        fk_ref = f"{m.group(1)}.{m.group(2)}"

                writer.writerow([
                    table_name,
                    col,
                    col_type,
                    constraints,
                    "yes" if is_pk else "no",
                    "yes" if is_fk else "no",
                    fk_ref,
                    "yes" if is_unique else "no",
                    table_desc,
                ])

        return output.getvalue()


def _field_notes(constraints: str) -> str:
    """Return a short emoji annotation string summarising a column's key constraints."""
    upper = constraints.upper()
    if "PRIMARY KEY" in upper:
        return "🔑 Primary key"
    parts = []
    if "REFERENCES" in upper:
        m = re.search(r"REFERENCES\s+(\w+)\s*\((\w+)\)", constraints, re.IGNORECASE)
        if m:
            parts.append(f"🔗 FK → `{m.group(1)}.{m.group(2)}`")
        else:
            parts.append("🔗 Foreign key")
    if "UNIQUE" in upper:
        parts.append("✨ Unique")
    if "NOT NULL" in upper:
        parts.append("✅ Required")
    return " · ".join(parts) if parts else ""
