"""
Output exporters: Mermaid ER diagrams and SQLAlchemy ORM model code generation.
"""

import re
from datetime import datetime, timezone


class MermaidExporter:
    """Generates Mermaid erDiagram notation from analysis results."""

    _TYPE_MAP = {
        "INTEGER": "int",
        "TEXT": "string",
        "VARCHAR": "string",
        "BOOLEAN": "boolean",
        "DECIMAL": "float",
        "NUMERIC": "float",
        "TIMESTAMP": "datetime",
        "BLOB": "bytes",
        "FLOAT": "float",
        "REAL": "float",
    }

    def _mermaid_type(self, sql_type: str) -> str:
        """Map a SQL type string to a Mermaid type keyword."""
        upper = sql_type.upper()
        for key, val in self._TYPE_MAP.items():
            if upper.startswith(key):
                return val
        return "string"

    def _extract_fk_pairs(self, entities: list) -> list:
        """Return list of (from_table, to_table, label) for FK relationships."""
        table_names = {e["name"] for e in entities}
        pairs = []
        for entity in entities:
            for field in entity.get("fields", []):
                constraints = field.get("constraints", "")
                match = re.search(
                    r"REFERENCES\s+(\w+)\s*\(", constraints, re.IGNORECASE
                )
                if match:
                    target = match.group(1)
                    if target in table_names:
                        pairs.append(
                            (entity["name"], target, field["name"])
                        )
        return pairs

    def generate(self, analysis: dict) -> str:
        """Generate a Mermaid erDiagram block from an analysis result."""
        entities = analysis.get("entities", [])
        ui_type = analysis.get("ui_type", "Unknown UI")

        lines = [
            "---",
            f"title: {ui_type} — ER Diagram",
            "---",
            "erDiagram",
        ]

        for entity in entities:
            lines.append(f"    {entity['name']} {{")
            for field in entity.get("fields", []):
                mtype = self._mermaid_type(field["type"])
                fname = field["name"]
                constraints = field.get("constraints", "")
                suffix = ""
                if "PRIMARY KEY" in constraints.upper():
                    suffix = " PK"
                elif "REFERENCES" in constraints.upper():
                    suffix = " FK"
                lines.append(f"        {mtype} {fname}{suffix}")
            lines.append("    }")
            lines.append("")

        fk_pairs = self._extract_fk_pairs(entities)
        for from_table, to_table, col in fk_pairs:
            lines.append(f'    {to_table} ||--o{{ {from_table} : "{col}"')

        return "\n".join(lines)


class SQLAlchemyExporter:
    """Generates SQLAlchemy 2.x ORM model code from analysis results."""

    _TYPE_MAP = {
        "INTEGER": "Integer",
        "TEXT": "Text",
        "VARCHAR": "String",
        "BOOLEAN": "Boolean",
        "DECIMAL": "Numeric",
        "NUMERIC": "Numeric",
        "TIMESTAMP": "DateTime",
        "BLOB": "LargeBinary",
        "FLOAT": "Float",
        "REAL": "Float",
    }

    def _sa_type(self, sql_type: str) -> str:
        """Map a SQL type string to a SQLAlchemy column type expression."""
        upper = sql_type.upper()
        for key, val in self._TYPE_MAP.items():
            if upper.startswith(key):
                length_match = re.search(r"\(([^)]+)\)", sql_type)
                if length_match and key in ("VARCHAR", "DECIMAL", "NUMERIC"):
                    return f"{val}({length_match.group(1)})"
                return val
        return "String"

    def _class_name(self, table_name: str) -> str:
        """Convert a snake_case table name to a PascalCase class name."""
        return "".join(word.capitalize() for word in table_name.split("_"))

    def generate(self, analysis: dict) -> str:
        """Generate SQLAlchemy 2.x ORM model code."""
        entities = analysis.get("entities", [])
        ui_type = analysis.get("ui_type", "Unknown UI")
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        lines = [
            f"# SQLAlchemy ORM models for: {ui_type}",
            f"# Generated by Screenshot2SQL on {ts}",
            "",
            "from sqlalchemy import (",
            "    Column, Integer, String, Text, Boolean,",
            "    Numeric, DateTime, Float, LargeBinary, ForeignKey,",
            ")",
            "from sqlalchemy.orm import DeclarativeBase, relationship",
            "",
            "",
            "class Base(DeclarativeBase):",
            "    pass",
        ]

        for entity in entities:
            class_name = self._class_name(entity["name"])
            desc = entity.get("description", "")
            lines.append("")
            lines.append("")
            if desc:
                lines.append(f"# {desc}")
            lines.append(f"class {class_name}(Base):")
            lines.append(f'    __tablename__ = "{entity["name"]}"')
            lines.append("")

            for field in entity.get("fields", []):
                fname = field["name"]
                sa_type = self._sa_type(field["type"])
                constraints = field.get("constraints", "")

                col_args = [sa_type]

                fk_match = re.search(
                    r"REFERENCES\s+(\w+)\s*\((\w+)\)", constraints, re.IGNORECASE
                )
                if fk_match:
                    col_args.append(
                        f'ForeignKey("{fk_match.group(1)}.{fk_match.group(2)}")'
                    )

                if "PRIMARY KEY" in constraints.upper():
                    col_args.append("primary_key=True")
                if "AUTOINCREMENT" in constraints.upper():
                    col_args.append("autoincrement=True")
                if (
                    "NOT NULL" in constraints.upper()
                    and "PRIMARY KEY" not in constraints.upper()
                ):
                    col_args.append("nullable=False")
                if "UNIQUE" in constraints.upper():
                    col_args.append("unique=True")

                default_match = re.search(
                    r"DEFAULT\s+([^\s,)]+)", constraints, re.IGNORECASE
                )
                if default_match:
                    dv = default_match.group(1).strip("'\"")
                    if dv.upper() == "CURRENT_TIMESTAMP":
                        col_args.append("default=None  # use func.now() in production")
                    elif dv.upper() in ("FALSE", "0"):
                        col_args.append("default=False")
                    elif dv.upper() in ("TRUE", "1"):
                        col_args.append("default=True")
                    elif re.match(r"^-?\d+$", dv):
                        col_args.append(f"default={dv}")
                    else:
                        col_args.append(f'default="{dv}"')

                lines.append(f"    {fname} = Column({', '.join(col_args)})")

            lines.append("")
            lines.append(f"    def __repr__(self) -> str:")
            lines.append(
                f'        return f"<{class_name} id={{self.id}}>"'
                if any(f["name"] == "id" for f in entity.get("fields", []))
                else f'        return f"<{class_name}>"'
            )

        lines.append("")
        return "\n".join(lines)
