"""
Prisma schema + TypeScript interface exporter.

Generates a valid prisma/schema.prisma file and standalone TypeScript
interfaces from an analysis result — useful for teams building on
Prisma ORM or Next.js stacks.
"""

import re
from datetime import datetime, timezone


class PrismaExporter:
    """Generates Prisma schema and TypeScript interfaces from analysis results."""

    _PRISMA_TYPE_MAP = {
        "INTEGER":   "Int",
        "BIGINT":    "BigInt",
        "TEXT":      "String",
        "VARCHAR":   "String",
        "BOOLEAN":   "Boolean",
        "DECIMAL":   "Decimal",
        "NUMERIC":   "Decimal",
        "TIMESTAMP": "DateTime",
        "BLOB":      "Bytes",
        "FLOAT":     "Float",
        "REAL":      "Float",
        "JSON":      "Json",
    }

    _TS_TYPE_MAP = {
        "INTEGER":   "number",
        "BIGINT":    "bigint",
        "TEXT":      "string",
        "VARCHAR":   "string",
        "BOOLEAN":   "boolean",
        "DECIMAL":   "number",
        "NUMERIC":   "number",
        "TIMESTAMP": "Date",
        "BLOB":      "Buffer",
        "FLOAT":     "number",
        "REAL":      "number",
        "JSON":      "unknown",
    }

    def _prisma_type(self, sql_type: str) -> str:
        """Map a SQL type string to the equivalent Prisma scalar type."""
        upper = sql_type.upper()
        for key, val in self._PRISMA_TYPE_MAP.items():
            if upper.startswith(key):
                return val
        return "String"

    def _ts_type(self, sql_type: str) -> str:
        """Map a SQL type string to the equivalent TypeScript primitive type."""
        upper = sql_type.upper()
        for key, val in self._TS_TYPE_MAP.items():
            if upper.startswith(key):
                return val
        return "string"

    def _model_name(self, table_name: str) -> str:
        """Convert snake_case table name to PascalCase Prisma model name."""
        return "".join(word.capitalize() for word in table_name.split("_"))

    def _build_fk_map(self, entities: list) -> dict:
        """Return {table_name: [(fk_col, target_table, target_col)]} for all FK fields."""
        table_names = {e["name"] for e in entities}
        fk_map: dict = {}
        for entity in entities:
            for field in entity.get("fields", []):
                m = re.search(
                    r"REFERENCES\s+(\w+)\s*\((\w+)\)",
                    field.get("constraints", ""),
                    re.IGNORECASE,
                )
                if m and m.group(1) in table_names:
                    fk_map.setdefault(entity["name"], []).append(
                        (field["name"], m.group(1), m.group(2))
                    )
        return fk_map

    def generate_prisma(self, analysis: dict) -> str:
        """
        Generate a prisma/schema.prisma file.

        Uses SQLite as the datasource provider (matches the rest of the project).
        """
        ui_type = analysis.get("ui_type", "Unknown UI")
        entities = analysis.get("entities", [])
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        fk_map = self._build_fk_map(entities)

        lines = [
            f"// Prisma schema for: {ui_type}",
            f"// Generated by Screenshot2SQL on {ts}",
            "",
            "generator client {",
            '  provider = "prisma-client-js"',
            "}",
            "",
            "datasource db {",
            '  provider = "sqlite"',
            '  url      = env("DATABASE_URL")',
            "}",
            "",
        ]

        for entity in entities:
            table = entity["name"]
            model_name = self._model_name(table)
            desc = entity.get("description", "")

            if desc:
                lines.append(f"/// {desc}")
            lines.append(f"model {model_name} {{")

            fk_cols = {fk[0] for fk in fk_map.get(table, [])}

            for field in entity.get("fields", []):
                col = field["name"]
                col_type = field["type"]
                constraints = field.get("constraints", "")
                upper_c = constraints.upper()
                prisma_t = self._prisma_type(col_type)

                attrs = []

                if "PRIMARY KEY" in upper_c:
                    attrs.append("@id")
                    if "AUTOINCREMENT" in upper_c:
                        attrs.append("@default(autoincrement())")

                if "UNIQUE" in upper_c:
                    attrs.append("@unique")

                if "DEFAULT CURRENT_TIMESTAMP" in upper_c:
                    attrs.append("@default(now())")
                else:
                    dm = re.search(r"DEFAULT\s+'([^']*)'", constraints, re.IGNORECASE)
                    if dm:
                        attrs.append(f'@default("{dm.group(1)}")')
                    else:
                        dm2 = re.search(r"DEFAULT\s+(TRUE|FALSE)", constraints, re.IGNORECASE)
                        if dm2:
                            attrs.append(f"@default({dm2.group(1).lower()})")
                        else:
                            dm3 = re.search(r"DEFAULT\s+(\d+)", constraints, re.IGNORECASE)
                            if dm3:
                                attrs.append(f"@default({dm3.group(1)})")

                is_optional = (
                    "NOT NULL" not in upper_c
                    and "PRIMARY KEY" not in upper_c
                )

                optional_mark = "?" if is_optional else ""
                attr_str = ("  " + "  ".join(attrs)) if attrs else ""
                lines.append(
                    f"  {col}  {prisma_t}{optional_mark}{attr_str}".rstrip()
                )

            # Relation fields (object references)
            for fk_col, target_table, target_col in fk_map.get(table, []):
                target_model = self._model_name(target_table)
                lines.append(
                    f"  {target_table}  {target_model}?  "
                    f"@relation(fields: [{fk_col}], references: [{target_col}])"
                )

            # Reverse relation arrays (one-to-many back-refs)
            for other in entities:
                if other["name"] == table:
                    continue
                for fk_col, tgt, _ in fk_map.get(other["name"], []):
                    if tgt == table:
                        other_model = self._model_name(other["name"])
                        lines.append(f"  {other['name']}  {other_model}[]")
                        break

            if table:
                lines.append(f'  @@map("{table}")')
            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def generate_typescript(self, analysis: dict) -> str:
        """
        Generate TypeScript interfaces for all entities.

        Produces one exported interface per table plus a union type.
        """
        ui_type = analysis.get("ui_type", "Unknown UI")
        entities = analysis.get("entities", [])
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        lines = [
            f"// TypeScript interfaces for: {ui_type}",
            f"// Generated by Screenshot2SQL on {ts}",
            "",
        ]

        interface_names = []

        for entity in entities:
            model_name = self._model_name(entity["name"])
            interface_names.append(model_name)
            desc = entity.get("description", "")

            if desc:
                lines.append(f"/** {desc} */")
            lines.append(f"export interface {model_name} {{")

            for field in entity.get("fields", []):
                col = field["name"]
                constraints = field.get("constraints", "")
                upper_c = constraints.upper()
                ts_type = self._ts_type(field["type"])

                is_optional = (
                    "NOT NULL" not in upper_c
                    and "PRIMARY KEY" not in upper_c
                )
                optional = "?" if is_optional else ""
                lines.append(f"  {col}{optional}: {ts_type};")

            lines.append("}")
            lines.append("")

        if interface_names:
            union = " | ".join(interface_names)
            lines.append(f"export type AnyEntity = {union};")
            lines.append("")

        return "\n".join(lines)
